# Generated by Django 6.0.3 on 2026-06-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
    ]
