# Generated by Django 6.0.3 on 2026-06-03 12:44

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/logos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='todolist_ta_user_id_d957b2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed'], name='todolist_ta_is_comp_a555d7_idx'),
        ),
    ]
