# Generated by Django 6.0.3 on 2026-06-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_options_task_created_at_task_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='todolist_ta_user_id_d957b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='todolist_ta_is_comp_a555d7_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='task_logos/'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
